server:
  port: 8761
  
eureka:
  server:
    enable-self-preservation: false
  instance:
    #标记通过IP注册服务
    prefer-ip-address: true
    #hostname: ${spring.cloud.client.ipAddress}
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #springboot2.0以后的配置
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/